#!/usr/bin/expect -f
spawn dpkg-reconfigure exim4-config
expect "General type of mail configuration: "
send "1\r"
expect "System mail name: "
send "yourdomain.com\r"
expect "IP-addresses to listen on for incoming SMTP connections: "
send "127.0.0.1\r"
expect "Other destinations for which mail is accepted: "
send "yourdomain.com\r"
expect "Domains to relay mail for: "
send "\r"
expect "Machines to relay mail for: "
send "\r"
expect "Keep number of DNS-queries minimal (Dial-on-Demand)?"
send "no\r"
expect "Delivery method for local mail: "
send "2\r"
expect "Split configuration into small files?"
send "no\r"
expect "Root and postmaster mail recipient: "
send "\r"
expect "invoke-rc.d: policy-rc.d denied execution of restart."
